name: yuejuan-macos

on:
  workflow_dispatch:
    inputs:
      quality:
        description: 'Build quality: stable or insider'
        required: false
        default: 'stable'

env:
  APP_NAME: Yuejuan
  APP_QUALITY: ${{ inputs.quality || 'stable' }}
  ASSETS_REPOSITORY: https://github.com/qinglion/yuejuan-binaries
  VERSIONS_REPOSITORY: https://github.com/qinglion/yuejuan-versions

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: macos-13
            arch: x64
          # - runner: macos-14
          #   arch: arm64
    runs-on: ${{ matrix.runner }}
    env:
      VSCODE_ARCH: ${{ matrix.arch }}
      # Speed up sqlite3 binary download in install
      npm_config_node_sqlite3_binary_host_mirror: https://registry.npmmirror.com/-/binary/sqlite3/
    steps:
      - name: Checkout builder
        uses: actions/checkout@v4

      - name: Setup Node.js 14 (fermium)
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build and collect assets
        env:
          GITHUB_TOKEN: ${{ secrets.STRONGER_GITHUB_TOKEN }}
          # macOS signing/notarization via P12 data (preferred)
          CERTIFICATE_OSX_P12_DATA: ${{ secrets.CERTIFICATE_OSX_P12_DATA }}
          CERTIFICATE_OSX_P12_PASSWORD: ${{ secrets.CERTIFICATE_OSX_P12_PASSWORD }}
          CERTIFICATE_OSX_ID: ${{ secrets.CERTIFICATE_OSX_ID }}
          CERTIFICATE_OSX_APP_PASSWORD: ${{ secrets.CERTIFICATE_OSX_APP_PASSWORD }}
          CERTIFICATE_OSX_TEAM_ID: ${{ secrets.CERTIFICATE_OSX_TEAM_ID }}
        run: |
          bash build.sh

      - name: Prepare checksums
        run: bash prepare_checksums.sh

      - name: Upload to OSS
        env:
          OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
          OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          OSS_BUCKET_NAME: ${{ secrets.OSS_BUCKET_NAME }}
          OSS_ENDPOINT: ${{ secrets.OSS_ENDPOINT }}
          OSS_REGION: ${{ secrets.OSS_REGION }}
          VSCODE_PLATFORM: darwin
          PUBLIC_DOWNLOAD_DOMAIN: d.qinglion.com
        run: bash upload_to_oss.sh
        # Required step; script fails if missing creds
      - name: Update versions repo
        env:
          SHOULD_BUILD: 'yes'
          GITHUB_TOKEN: ${{ secrets.STRONGER_GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
          PUBLIC_DOWNLOAD_DOMAIN: ${{ secrets.PUBLIC_DOWNLOAD_DOMAIN }}
          VSCODE_PLATFORM: darwin
        run: bash release.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: yuejuan-macos-${{ matrix.arch }}
          path: assets/
          retention-days: 7


